[".asdf"]
  exact = true
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/asdf-vm/asdf.git"
  clone.args = ["--branch v0.9.0"]
  pull.args = ["--rebase", "-s", "recursive", "-X ours"]
[".vim/autoload/plug.vim"]
  exact = true
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".zinit/bin"]
  exact = true
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/zdharma-continuum/zinit.git"
  pull.args = ["--rebase", "-s", "recursive", "-X ours"]
