[".asdf"]
  type = "archive"
  refreshPeriod = "168h"
  exact = true
  stripComponents = 1
  url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.11.3.tar.gz"
[".vim/autoload/plug.vim"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".zinit/bin"]
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/zdharma-continuum/zinit.git"
[".config/fzf/fzf-zsh-plugin"]
  type = "git-repo"
  refreshPeriod = "168h"
  url = "https://github.com/unixorn/fzf-zsh-plugin.git"
[".config/nnn/plugins/.cbcp"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/.cbcp"
  refreshPeriod = "168h"
[".config/nnn/plugins/.iconlookup"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/.iconlookup"
  refreshPeriod = "168h"
[".config/nnn/plugins/.nmv"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/.nmv"
  refreshPeriod = "168h"
[".config/nnn/plugins/.nnn-plugin-helper"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/.nnn-plugin-helper"
  refreshPeriod = "168h"
[".config/nnn/plugins/.ntfy"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/.ntfy"
  refreshPeriod = "168h"
[".config/nnn/plugins/bulknew"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/bulknew"
  refreshPeriod = "168h"
[".config/nnn/plugins/cdpath"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/cdpath"
  refreshPeriod = "168h"
[".config/nnn/plugins/diffs"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/diffs"
  refreshPeriod = "168h"
[".config/nnn/plugins/gitroot"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/gitroot"
  refreshPeriod = "168h"
[".config/nnn/plugins/finder"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/finder"
  refreshPeriod = "168h"
[".config/nnn/plugins/fzcd"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/fzcd"
  refreshPeriod = "168h"
[".config/nnn/plugins/fzhist"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/fzhist"
  refreshPeriod = "168h"
[".config/nnn/plugins/fzopen"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/fzopen"
  refreshPeriod = "168h"
[".config/nnn/plugins/nuke"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/nuke"
  refreshPeriod = "168h"
[".config/nnn/plugins/organize"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/organize"
  refreshPeriod = "168h"
[".config/nnn/plugins/preview-tui"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/preview-tui"
  refreshPeriod = "168h"
[".config/nnn/plugins/pskill"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/pskill"
  refreshPeriod = "168h"
[".config/nnn/plugins/renamer"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/renamer"
  refreshPeriod = "168h"
[".config/nnn/plugins/suedit"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/suedit"
  refreshPeriod = "168h"
[".config/nnn/plugins/togglex"]
  type = "file"
  exact = true
  url = "https://raw.githubusercontent.com/jarun/nnn/master/plugins/togglex"
  refreshPeriod = "168h"
