[".asdf"]
url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.12.0.tar.gz"
type = "archive"
exact = true
stripComponents = 1
[".vim/autoload/plug.vim"]
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
type = "file"
exact = true
refreshPeriod = "168h"
[".config/zsh/.zi/bin"]
url = "https://github.com/z-shell/zi.git"
type = "git-repo"
refreshPeriod = "168h"
[".config/fzf/fzf-zsh-plugin"]
url = "https://github.com/unixorn/fzf-zsh-plugin.git"
type = "git-repo"
refreshPeriod = "168h"
[".config/yazi/plugins/starship.yazi"]
url = "https://github.com/Rolv-Apneseth/starship.yazi.git"
type = "git-repo"
refreshPeriod = "168h"
[".local/share/eclipse/eclipse-java-google-style.xml"]
url = "https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml"
type = "file"
exact = true
[".local/share/eclipse/lombok.jar"]
url = "https://projectlombok.org/downloads/lombok.jar"
type = "file"
exact = true
